config/routes.rb
ActiveAdminNestedSet::Application.routes.draw do
  root :to => 'documents#index'
  resources :categories, :documents

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :presence => true

  has_many :documents, :through => :categories_documents
  acts_as_nested_set
end

app/models/document.rb
class Document < ActiveRecord::Base
  validates :name, :file_name, :category_id, :presence => true
  #validates_attachment_content_type :doc, :pdf
  #has_attached_file :uploader, :url => "/:file_name"

  has_many :categories, :through => :categories_documents
end

app/models/hierarchy.rb
class Hierarchy < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.create!(:name => params[:name])
    if params[:parent_id] != nil
          @category = move_to_child_of(Category.find(params[:parent_id]))
    end

  end

  def index
    @hierarchies = Category.roots
    @categories = Category.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render json: @categories }
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController

    # GET /documents
  # GET /documents.json
  def index
    if params[:id] == nil
      @documents = Document.all
    else
      @documents = Document.where(:category_id => params[:id])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @documents }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @document }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @document = Document.new
    @categories = Category.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @document }
    end
  end

  # GET /products/1/edit
  def edit
    @document = Document.find(params[:id])
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @document = Document.new(params[:document])

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Product was successfully updated.' }
        format.json { render json: @document, status: :created, location: @document }
      else
        format.html { render action: "new" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @document = Document.find(params[:id])

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html { redirect_to @document, notice: 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :ok }
    end
  end
end

app/controllers/hierarchies_controller.rb
class HierarchyController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/hierarchy_helper.rb
module HierarchyHelper
end

app/views/admin/categories/_create_category_form.erb
<%= semantic_form_for [:admin, @hierarchy, @category] do |f| %>


    <%= f.inputs "Hierarchies and Categories" do %>
        <%= f.input :name %>
        <%= f.input :parent_id, :label => "Category", :as => :select, :collection => Category.all %>
        <p style="margin-left: 267px"> If you don't specify Category, it will create <b>Hierarchy</b> object, that is on root level</p>

    <% end %>
    <%= f.buttons do %>
        <%= f.submit %>
    <% end %>

<%end%>

app/views/admin/documents/_create_document_form.erb
<%= semantic_form_for [:admin, @document], :html => { :multipart => true } do |f| %>

    <%= f.inputs "Managing documents" do %>
        <%= f.input :name %>
        <%= f.input :description%>
        <%= f.input :category_id, :label => "Select categories",:as => :select, :collection => Category.all %>
        <%= f.input :file_name, :label => "Specify URL of file", :required => true, :as => :url %>

    <% end %>
    <%= f.buttons do %>
        <%= f.submit %>
    <% end %>

<%end%>

app/views/admin/hierarchies/_create_hierarchy_form.erb
<%= semantic_form_for [:admin, @hierarchy] do |f| %>

    <%= f.inputs "Create multiple hierarchies" do %>
        <%= f.input :name, :label => "Name of hierarchy" %>
    <% end %>
    <%= f.buttons do %>
        <li class="save">
            <%= f.submit "Create Hierarchy" %>
        <li>
    <% end %>
<%end%>

app/views/categories/_category.html.erb
<li class="collapsibleList">
  <%= link_to h(category.name),
              :controller => 'documents',
              :action => 'index', :id => category.id %>
  <% if category.children.empty? %>

  <% else %>
      <ul>
        <%= render :partial => 'categories/category',
                   :collection => category.children %>
      </ul>
  <% end %>
</li>

app/views/categories/show.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Parent:</b>
  <%= @category.parent_id %>
</p>

<p>
  <b>Num of children:</b>
  <%= @category.children.length %>
</p>

app/views/documents/_form.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2>Počet chýb: <%= @document.errors.count %>, nie je možné uložiť vytvorený objekt </h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <b><%= f.label :name %></b><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <b><%= f.label :description %></b><br />
    <%= f.text_area :description%>
  </div>
  <div class="field">
    <b><%= f.label :category_id %></b><br/>
    <%= collection_select(:category, :document_id, Category.all, :id, :name )%>
  </div>
  <div class="field">
    <b><%= f.label :file_name %></b><br />
    <%= f.text_field :file_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.erb
<div class="headerDocs">
  <h2><%= @document.name %></h2>
</div>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
    <div >
      <div class="headerDocs">
        <h2>Dokumenty (<%= @documents.length %>)</h2>
      </div>

      <div class="tableDocs">
      <table>
        <% if @documents.length == 0 %>
            <p>Kategória neobsahuje dokumenty</p>
        <% else %>
        <tr id="columns_names_separator">
          <td><b>Názov dokumentu</b></td>
          <td><b>Popis dokumentu</b></td>
          <td><b>Akcie nad dokumentom</b></td>
        </tr>
        <% @documents.each do |document| %>
            <tr class="<%= cycle('list_line_odd', 'list_line_even') %>" >
              <td>
                <b class="docName"><%= document.name %></b>
              </td>
              <td >
                <%= document.description %>
              </td>
              <td class="list_actions" >
                <%= link_to 'Show', document %><br/>
                <%= link_to 'Edit', edit_document_path(document) %><br/>
                <%= link_to 'Destroy', document,
                            :confirm => 'Are you sure?',
                            :method => :delete %>
              </td>
            </tr>
        <% end %>
        <% end %>
      </table>
        </div>
    </div>
    <br />
    <!-- <%= link_to 'New document', new_document_path %> -->

app/views/documents/new.erb
<h1>Nový dokument</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.erb
<div class="headerDocs">
  <h2><%= @document.name %></h2>
</div>

<p id="notice"><%= notice %></p>
<p>
  <b>Name:</b>
  <%= @document.name %>
</p>

<p>
  <b>Description:</b>
  <%= @document.description %>
</p>

<p>
  <b>Category:</b>
  <%= Category.find(@document.category_id).name %>
</p>

<p>
  <b>File URL:</b>
  <%=link_to @document.file_name,:url => @document.file_name %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', @documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <!-- <script type="text/javascript" src="CollapsibleLists.js"></script>  -->

<head>
  <title>ActiveAdminNestedSet</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="head">
  <b>Multikategorizácia dokumentov</b>
  <a id="admin_button" href="/admin">Admin</a>
</div>
<div id="tree_view" >
  <div class="header">
        <h2>Kategórie</h2>
  </div>
    <ul class="collapsibleList">
        <b><%= link_to 'Všetky dokumenty', :controller => 'documents',
              :action => 'index', :id => nil %></b>
        <%= render :partial => 'categories/category',
               :collection => Category.find_all_by_parent_id(nil) %>
    </ul>
</div>

<div id="placeholder" >
    <%= yield %>
</div>

</body>
</html>